index/urls.py
from django.conf.urls import url

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category-detail'),
    url(r'^search/$', views.UserSearchView.as_view(), name='person-search'),
]

meetme_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('account_ext.urls')),
    url(r'^', include('allauth.urls')),

    url(r'^', include('index.urls')),
    url(r'^meeting/', include('meetings.urls')),
    url(r'^comment/', include('comments.urls')),

    url(r'^', include('django.contrib.flatpages.urls')),
]

account_ext/models.py
# coding: utf-8

import random
import datetime

from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.utils.translation import pgettext, ugettext as _
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django.contrib.sites.shortcuts import get_current_site

from allauth.account.adapter import get_adapter
from index.models import Category

from .managers import SMSConfirmationManager

# Create your models here.

class User(AbstractUser):
    photo = models.ImageField(_('Фото'), upload_to='users/%Y/%m/%d', blank=True, null=True)
    nickname = models.CharField(_('Ник'), max_length=250, blank=True, null=True)
    is_public = models.BooleanField(_('Публичный?'), default=False)
    about = models.TextField(_('О себе'), blank=True, null=True)
    categories = models.ManyToManyField(Category, verbose_name=_('Категории'), blank=True)
    rate = models.FloatField(_('Оценка'), default=0.0)
    is_approved = models.BooleanField(_('Подтвержден?'), default=False)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        res = self.first_name
        res += " " + self.last_name
        res = res.strip()
        if not len(res):
            res = self.username
        return res

    def recalc_rate(self):
        from comments.models import Comment
        self.rate =  Comment.objects.filter(cto=self).aggregate(models.Avg('rate'))['rate__avg']
        self.save()


class SMSConfirmation(models.Model):
    user = models.ForeignKey(User,
                                      verbose_name=_('User'),
                                      on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name=_('created'),
                                   default=timezone.now)
    sent = models.DateTimeField(verbose_name=_('sent'), null=True)
    key = models.IntegerField(verbose_name=_('key'))

    objects = SMSConfirmationManager()

    class Meta:
        verbose_name = _("SMS подтверждение")
        verbose_name_plural = _("SMS подтверждения")

    def __unicode__(self):
        return _("SMS подтверждение для %s") % self.user

    @classmethod
    def create(cls, user):
        key = random.randint(0000, 9999)
        return cls._default_manager.create(user=user,
                                           key=key)

    def key_expired(self):
        try: seconds = settings.SMS_CONFIRMATION_EXPIRE_SECONDS
        except: seconds = 3*60

        expiration_date = self.sent \
            + datetime.timedelta(seconds=seconds)
        return expiration_date <= timezone.now()
    key_expired.boolean = True

    def key_expired_at(self):
        try: seconds = settings.SMS_CONFIRMATION_EXPIRE_SECONDS
        except: seconds = 3*60

        delta = (timezone.now() - self.sent).seconds
        if delta < seconds:
            return seconds - delta
        return 0

    def confirm(self, request):
        if not self.key_expired() and not self.user.is_active:
            user = self.user
            get_adapter(request).confirm_sms(request, user)
            #signals.email_confirmed.send(sender=self.__class__,
            #                             request=request,
            #                             email_address=email_address)
            return user

    def send(self, request=None, signup=False):
        get_adapter(request).send_confirmation_sms(request, self, signup)
        #signals.email_confirmation_sent.send(sender=self.__class__,
        #                                     request=request,
        #                                     confirmation=self,
        #                                     signup=signup)


@receiver(pre_save, sender=User)
def notify_approvement(sender, **kwargs):
    instance = kwargs.pop("instance")
    if instance.id:
        old_is_approved = instance.__class__.objects.get(id=instance.id).is_approved
        if instance.is_approved != old_is_approved and instance.is_approved and instance.email:
            current_site = get_current_site(request=None)
            text = 'Ваша учетная запись подтверждена. <a href="http://%s%s">%s</a>' % (current_site.domain, reverse('person-detail', kwargs={"pk":instance.id}), str(instance))
            send_mail(
                'Изменение статуса',
                text,
                'no-reply@meetmehub.com',
                [instance.email],
                fail_silently=False,
                html_message=text,
            )

templates/index/anketa.html
{% extends "base_ajax.html" %}

{% load i18n %}
{% load account %}

{% block title %}{% trans "Запрос отправлен" %}{% endblock title %}

{% block content %}
    <div class="modal-header">
        <h5 class="modal-title">{% trans "Запрос отправлен" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p>{% blocktrans %}Ваш запрос успешно отправлен. В ближайшее время наш менеджер свяжется с вами.{% endblocktrans %}</p>
    </div>
    <div class="modal-footer">
       <button type="button" data-dismiss="modal" class="btn btn-primary">{% trans 'Закрыть' %}</button>
    </div>
{% endblock %}

templates/index/category_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index:index' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item active">{{ category.title }}</li>
        </ol>
    </div>
    <div class="container pb-5">
        <p class="h1 text-center pt-2"><span class="text-highlighted">{{ object.title }}</span></p>
        <div class="row justify-content-center pt-4">
        {% for object in category.user_set.all %}
            <div class="col-12 col-md-4 mt-4">
                <a href="{% url 'person-detail' object.id %}"><img class="big-photo grayed" src="{% if object.photo %}{{ object.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}" alt=""></a>
                <p class="text-center mt-3">
                    <input type="number" class="star-rating" value="{{ object.rate|floatformat:0 }}" data-readonly />
                </p>
                <p class="h4 mt-3 text-center person-title">{{ object }}</p>
                <p class="person-info">{{ object.about|default_if_none:""|safe }}</p>
                <p class="text-center">
                    <a href="{% url 'person-detail' object.id %}" class="btn btn-primary pl-5 pr-5">{% trans 'Подробнее' %}</a>
                </p>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-rating-input.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input.star-rating').rating({
                iconLib: "fa fa-2x",
                activeIcon: "fa-star",
                inactiveIcon: "fa-star-o",
                clearableIcon: "fa-trash-o"
            });
        });
    </script>
{% endblock extra_js %}

templates/index/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/slick-theme.css' %}"/>
{% endblock extra_css %}

{% block content_index %}
    <div id="id-block1" class="container-fluid block1">
        <p class="mt-5 h1 text-center text-white"><span class="text-highlighted">Ближе к звездам с Meetme Hub!</span></p>
        <div class="row pt-5 geo">
            <div class="col-12 pt-3 col-md-6">
                <p class="text-white pl-4 text1">Первый в России онлайн-сервис для знакомств со знаменитостями.
                </p>
                <p class="text-white pl-4 mt-4 text2">Если Вам хочется высказать свое мнение, поближе познакомиться с
                    любимым блогером, провести время в компании известной личности, то сервис Meetme Hub поможет вам в
                    этом.</p>
                <p class="text-white pl-4 mt-4 text2 text-on-blue">Наша цель – сокращение дистанции между вами и
                    знаменитостями.</p>
                <p class="text-white pl-4 mt-4 text2">Встретить или пообщаться со знаменитостью может быть довольно трудно
                    из-за их напряженного графика и желания побыть вдалеке от публики. Благодаря нашему сервису, достаточно
                    указать интересующую личность и ввести параметры встречи – организацией займется команда Meetme Hub.</p>
                <p class="text-white pl-4 mt-4 text2 text-on-blue">Вы выбираете – мы организовываем</p>
                <p class="text-white pl-4 mt-4 text2">Воплощайте самые смелые идеи, станьте ближе к своим кумирам, совершите
                    долгожданное путешествие в мир грёз и творите добро со знаменитостями - 10% от средств, заработанных с
                    вашей встречи, будут переведены в партнерские благотворительные фонды:</p>
            </div>
            <div class="col-12 pb-5">
                <p class="mt-5 pt-5 h2 text-center text-white">Вы получите:</p>
                <div class="row mt-5 pt-3 pl-5 pr-5">
                    <div class="col-12 col-md-4 checked">
                        <span class="text-white">Впечатления от личной встречи со знаменитостью</span>
                    </div>
                    <div class="col-12 col-md-4 checked">
                        <span class="text-white">Возможность представить интересную идею в массы</span>
                    </div>
                    <div class="col-12 col-md-4 checked">
                        <span class="text-white">Способ продвижения товаров и услуг</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid block2">
        <div class="container pb-3">
            <p class="pt-5 h2 text-center text-white">Как это работает?</p>
            <div class="row pt-5 pb-5 justify-content-center">
                <div class="col-12 col-md-4 pt-5 text-center arrow-left">
                    <img class="info-icon" src="{% static 'img/img11.png' %}">
                    <p class="h3 text-white">Выберете публичную личность</p>
                </div>
                <div class="col-12 col-md-4 pt-5 text-center arrow-center">
                    <img class="info-icon" src="{% static 'img/img12.png' %}">
                    <p class="h3 text-white">Заполните заявку</p>
                </div>
                <div class="col-12 col-md-4 pt-5 text-center arrow-right">
                    <img class="info-icon" src="{% static 'img/img13.png' %}">
                    <p class="h3 text-white">Общайтесь</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid block3">
        <div class="container big-logo">
            <p class="mt-5 pt-5 h2 text-center text-white"><span
                    class="text-highlighted">В чем могут помочь знаменитости?</span></p>
            <div class="row mt-5 pt-4">
                <div class="col-2 text-center">
                    <p class="h0 text-white text-center">1</p>
                </div>
                <div class="col-8">
                    <p class="h4 text-white">Исполнить заветную мечту</p>
                    <p class="pt-3 text2 text-white">Личное знакомство, проведение интервью, совместное участие в
                        мероприятиях и т.п.<br><br>
                        Поверьте, согласованная встреча наиболее эффективна, когда собеседник расположен к вам и знает,
                        что от него ждут. В отличии от мимолетных и случайных бесед, вы сможете вести двусторонний
                        диалог на равных.
                    </p>
                </div>
            </div>
            <div class="row mt-5 justify-content-end">
                <div class="col-2 text-center">
                    <p class="h0 text-white text-center">2</p>
                </div>
                <div class="col-8">
                    <p class="h4 text-white">Рупор для коммуникации</p>
                    <p class="pt-3 text2 text-white">У вас давно созрела идея, которую нужно продвигать в массы. Отличное
                        начало – если она будет звучать из уст знаменитости.<br><br>
                        Будьте уверены, даже самая благородная и полезная идея будет восприниматься массами намного
                        лучше, если ее поддержат лидеры мнений и блогеры. Все начинается с народного доверия, ад обиться
                        его помогут авторитетные голоса и лица.
                    </p>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-2 text-center">
                    <p class="h0 text-white text-center">3</p>
                </div>
                <div class="col-8">
                    <p class="h4 text-white">Продвинуть свой продукт</p>
                    <p class="pt-3 text2 text-white">Спонсорские посты в блогах, брендовый контент в социальных сетях,
                        создание контента лидерами мнений.<br><br>
                        Любимым блогерам люди склонны верить больше, чем рекламе. 92% покупателей верят рекомендациям
                        других людей, даже незнакомых. Вы сможете наладить контакт с известной личностью и провести
                        маркетинговую компанию совместно.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid block4">
        <div class="container">
            {% if request.user and request.user.is_authenticated %}
            {% else %}
                <div class="container-fluid pt-3 pb-3 text-center">
                    <a id="id-signup-public" href="{% url 'account_signup_public' %}"
                       class="btn btn-big btn-primary">{% trans "Я публичная личность" %}</a>
                </div>
            {% endif %}
            <div class="h2 offset text-white text-center"><span class="text-highlighted">{% trans "Популярные" %}</span>
            </div>
            <div class="row mt-5">
                {% for item in popular %}
                    <div class="col-12 col-md-4 mt-4">
                        <a class="person-detail" href="{% url 'person-detail' item.id %}">
                            <img class="big-photo grayed" src="
                                    {% if item.photo %}{{ item.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}"
                                 alt="">
                            <p class="text-center mt-3">
                                <input type="number" class="star-rating" value="{{ item.rate|floatformat:0 }}"
                                       data-readonly/>
                            </p>
                            <p class="h4 mt-3 text-center person-title text-white">{{ item }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>

            <div class="h2 offset text-center text-white"><span class="text-highlighted">{% trans "Категории" %}</span>
            </div>
            <div class="row mt-5">
                {% for category in categories %}
                    <a href="{% url 'index:category-detail' pk=category.id %}"
                       class="col-12 col-md-4 text-center styled-link">
                        <img class="category-icon pt-5" src="{{ category.image.url }}">
                        <p class="h3 pt-3 pb-5 text-white">{{ category.title }} <span
                                class="badge badge-pill badge-default">{{ category.users_count }}</span></p>
                    </a>
                {% endfor %}
            </div>

            <div class="h2 offset text-center text-white"><span class="text-highlighted">{% trans "Партнеры" %}</span>
            </div>
            <div class="funds pt-5 pb-5">
                {% for fund in funds %}
                    <a class="d-block text-center" href="{{ fund.link }}"><img src="{{ fund.image.url }}"></a>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock content_index %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-rating-input.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.banners').slick({
                dots: true,
                infinite: true,
            });

            $('.funds').slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 1,
                centerMode: true,
                variableWidth: true,
                autoplay: true,
                autoplaySpeed: 2000,
            });

            if ("{{ ajax_after_done }}" != "") {
                $.get(
                    "{{ ajax_after_done }}",
                    function (data) {
                        $("#id-modal .modal-content").html(data["html"]);
                        if ($("#id-modal").is(":visible") == false) {
                            $("#id-modal").modal('show');
                        }
                    }
                );
            }

            $('input.star-rating').rating({
                iconLib: "fa fa-2x",
                activeIcon: "fa-star",
                inactiveIcon: "fa-star-o",
                clearableIcon: "fa-trash-o"
            });
        });
    </script>
{% endblock extra_js %}

templates/index/search.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load search %}

{% block content %}
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index:index' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item active">{{ q }}</li>
        </ol>
    </div>
    <div class="container pb-5">
        <div class="row justify-content-center ">
        {% if object_list %}
        {% for object in object_list %}
            <div class="col-12 col-md-4 mt-4">
                <img class="big-photo grayed" src="{% if object.photo %}{{ object.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}" alt="">
                <p class="text-center mt-3">
                    <input type="number" class="star-rating" value="{{ object.rate|floatformat:0 }}" data-readonly />
                </p>
                <p class="h4 mt-3 text-center person-title">{{ object|highlight:q }}</p>
                <p class="person-info">{{ object.about|highlight:q|safe }}</p>
                <p class="text-center">
                    <a href="{% url 'person-detail' object.id %}" class="btn btn-primary pl-5 pr-5">{% trans 'Подробнее' %}</a>
                </p>
            </div>
        {% endfor %}
        {% else %}
            <p class="h3 text-center">{% trans 'По вашему запросу ничего не найдено' %}</p>
        {% endif %}
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-rating-input.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input.star-rating').rating({
                iconLib: "fa fa-2x",
                activeIcon: "fa-star",
                inactiveIcon: "fa-star-o",
                clearableIcon: "fa-trash-o"
            });
        });
    </script>
{% endblock extra_js %}