account_ext/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from . import views


redirect_to_profile = views.RedirectView.as_view(url=reverse_lazy('account_profile'), permanent=False)

urlpatterns = [
    url(r"^login/$", views.login, name="account_login"),
    url(r"^signup/$", views.signup, name="account_signup"),
    url(r"^signup-public/$", views.signup_public, name="account_signup_public"),
    url(r"^accounts/profile/$", views.profile,
        name="account_profile"),
    url(r"^password/reset/done/$", views.password_reset_done,
        name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"),
    url(r"^password/reset/key/done/$", views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"),
    url(r"^accounts/profile/meetings/$", views.MeetingsListView.as_view(),
        name="account_profile_meetings"),

    url(r"^inactive/$", views.account_inactive, name="account_inactive"),
    url(r'^social/connections/$', redirect_to_profile, name='socialaccount_connections'),
    url(r'^login/cancelled/$', redirect_to_profile, name='socialaccount_login_cancelled'),
    url(r'^login/error/$', redirect_to_profile, name='socialaccount_login_error'),

    url(r'^profile/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='person-detail'),

    url(r'^approve/(?P<pk>\d+)/$', views.ApproveView.as_view(), name='person-approve'),
]

index/urls.py
from django.conf.urls import url

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category-detail'),
    url(r'^search/$', views.UserSearchView.as_view(), name='person-search'),
]

meetings/urls.py
from django.conf.urls import url

from . import views

app_name = 'meetings'
urlpatterns = [
#    url(r'^anketa/$', views.anketa, name='anketa'),
    url(r'create/$', views.MeetingCreateView.as_view(), name='create'),
    url(r'(?P<pk>\d+)/$', views.MeetingDetailView.as_view(), name='detail'),
]

meetme_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('account_ext.urls')),
    url(r'^', include('allauth.urls')),

    url(r'^', include('index.urls')),
    url(r'^meeting/', include('meetings.urls')),
    url(r'^comment/', include('comments.urls')),

    url(r'^', include('django.contrib.flatpages.urls')),
]

account_ext/models.py
# coding: utf-8

import random
import datetime

from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.utils.translation import pgettext, ugettext as _
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django.contrib.sites.shortcuts import get_current_site

from allauth.account.adapter import get_adapter
from index.models import Category

from .managers import SMSConfirmationManager

# Create your models here.

class User(AbstractUser):
    photo = models.ImageField(_('Фото'), upload_to='users/%Y/%m/%d', blank=True, null=True)
    nickname = models.CharField(_('Ник'), max_length=250, blank=True, null=True)
    is_public = models.BooleanField(_('Публичный?'), default=False)
    about = models.TextField(_('О себе'), blank=True, null=True)
    categories = models.ManyToManyField(Category, verbose_name=_('Категории'), blank=True)
    rate = models.FloatField(_('Оценка'), default=0.0)
    is_approved = models.BooleanField(_('Подтвержден?'), default=False)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        res = self.first_name
        res += " " + self.last_name
        res = res.strip()
        if not len(res):
            res = self.username
        return res

    def recalc_rate(self):
        from comments.models import Comment
        self.rate =  Comment.objects.filter(cto=self).aggregate(models.Avg('rate'))['rate__avg']
        self.save()


class SMSConfirmation(models.Model):
    user = models.ForeignKey(User,
                                      verbose_name=_('User'),
                                      on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name=_('created'),
                                   default=timezone.now)
    sent = models.DateTimeField(verbose_name=_('sent'), null=True)
    key = models.IntegerField(verbose_name=_('key'))

    objects = SMSConfirmationManager()

    class Meta:
        verbose_name = _("SMS подтверждение")
        verbose_name_plural = _("SMS подтверждения")

    def __unicode__(self):
        return _("SMS подтверждение для %s") % self.user

    @classmethod
    def create(cls, user):
        key = random.randint(0000, 9999)
        return cls._default_manager.create(user=user,
                                           key=key)

    def key_expired(self):
        try: seconds = settings.SMS_CONFIRMATION_EXPIRE_SECONDS
        except: seconds = 3*60

        expiration_date = self.sent \
            + datetime.timedelta(seconds=seconds)
        return expiration_date <= timezone.now()
    key_expired.boolean = True

    def key_expired_at(self):
        try: seconds = settings.SMS_CONFIRMATION_EXPIRE_SECONDS
        except: seconds = 3*60

        delta = (timezone.now() - self.sent).seconds
        if delta < seconds:
            return seconds - delta
        return 0

    def confirm(self, request):
        if not self.key_expired() and not self.user.is_active:
            user = self.user
            get_adapter(request).confirm_sms(request, user)
            #signals.email_confirmed.send(sender=self.__class__,
            #                             request=request,
            #                             email_address=email_address)
            return user

    def send(self, request=None, signup=False):
        get_adapter(request).send_confirmation_sms(request, self, signup)
        #signals.email_confirmation_sent.send(sender=self.__class__,
        #                                     request=request,
        #                                     confirmation=self,
        #                                     signup=signup)


@receiver(pre_save, sender=User)
def notify_approvement(sender, **kwargs):
    instance = kwargs.pop("instance")
    if instance.id:
        old_is_approved = instance.__class__.objects.get(id=instance.id).is_approved
        if instance.is_approved != old_is_approved and instance.is_approved and instance.email:
            current_site = get_current_site(request=None)
            text = 'Ваша учетная запись подтверждена. <a href="http://%s%s">%s</a>' % (current_site.domain, reverse('person-detail', kwargs={"pk":instance.id}), str(instance))
            send_mail(
                'Изменение статуса',
                text,
                'no-reply@meetmehub.com',
                [instance.email],
                fail_silently=False,
                html_message=text,
            )

meetings/forms.py
import parsedatetime as pdt

from django import forms
from django.utils.translation import pgettext, ugettext as _


from .models import Meeting


class MeetingCreateForm(forms.ModelForm):
    mdate = forms.CharField(label=_("Дата и время"), widget=forms.TextInput(attrs={"type": "text"}))

    class Meta:
        model = Meeting
        fields = '__all__'
        exclude = ["state",]

        widgets = {
            "mfrom": forms.HiddenInput(),
            "mto": forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = super(MeetingCreateForm, self).clean()
        cal = pdt.Calendar()
        date = self.cleaned_data.get('mdate', '').replace("T", " ")
        date, result = cal.parseDT(date)
        cleaned_data["mdate"] = date

        return cleaned_data

account_ext/views.py
from django.http import JsonResponse, Http404
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView, FormView, UpdateView, RedirectView, DetailView, DetailView, ListView
from django.contrib.auth import get_user_model
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import pgettext, ugettext as _
from django.contrib.admin.views.decorators import staff_member_required

from allauth.account import views
from allauth.account.utils import get_request_param, get_next_redirect_url
from allauth.exceptions import ImmediateHttpResponse

from comments.models import Comment
from meetings.forms import MeetingCreateForm
from meetings.models import Meeting

from .forms import LoginForm, SignupForm, SignupPublicForm, SMSForm, UserProfileForm, ApproveForm
from .models import SMSConfirmation

# Create your views here.

class AjaxOnlyResponseMixin(object):

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            html = super(AjaxOnlyResponseMixin, self).get(request, *args, **kwargs)
            return JsonResponse({"html": html.rendered_content})
        raise Http404


class LoginView(views.LoginView):
    form_class = LoginForm

    def dispatch(self, request, *args, **kwargs):
        try: del request.session["last_inactive_user"]
        except: pass
        if request.method == "GET" and not request.is_ajax():
            if request.user.is_authenticated:
                return redirect("account_profile")
            request.session['ajax_after_done'] = request.get_full_path()
            return redirect("index:index")
        return super(LoginView, self).dispatch(request, *args, **kwargs)

login = LoginView.as_view()


class SignupView(views.SignupView):
    form_class = SignupForm
    redirect_field_name = "next"

    def dispatch(self, request, *args, **kwargs):
        try: del request.session["last_inactive_user"]
        except: pass
        if request.method == "GET" and not request.is_ajax():
            if request.user.is_authenticated:
                return redirect("account_profile")
            request.session['ajax_after_done'] = request.get_full_path()
            return redirect("index:index")
        return super(SignupView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)

        redirect_field_name = self.redirect_field_name
        redirect_field_value = get_request_param(self.request,
                                                 redirect_field_name)
        context["form_action"] = reverse('account_signup')

        if redirect_field_value:
            context["redirect_field_value"] = redirect_field_value
        else:
            try: del context["redirect_field_value"]
            except: pass

        return context


signup = SignupView.as_view()


class SignupPublicView(SignupView):
    form_class = SignupPublicForm

    def get_context_data(self, **kwargs):
        context = super(SignupPublicView, self).get_context_data(**kwargs)
        context["form_action"] = reverse('account_signup_public')
        return context


signup_public = SignupPublicView.as_view()


class PasswordResetDoneView(AjaxOnlyResponseMixin, views.PasswordResetDoneView):
    pass

password_reset_done = PasswordResetDoneView.as_view()


class PasswordResetFromKeyView(views.PasswordResetFromKeyView):

    def dispatch(self, request, uidb36, key, **kwargs):
        if request.method == "GET" and not request.is_ajax():
            request.session['ajax_after_done'] = request.get_full_path()
            return redirect("index:index")
        return super(PasswordResetFromKeyView, self).dispatch(request,
                                                                  uidb36,
                                                                  key,
                                                                  **kwargs)

password_reset_from_key = PasswordResetFromKeyView.as_view()


class PasswordResetFromKeyDoneView(AjaxOnlyResponseMixin, views.PasswordResetFromKeyDoneView):
    pass

password_reset_from_key_done = PasswordResetFromKeyDoneView.as_view()


@method_decorator(login_required, name='dispatch')
class ProfileView(SuccessMessageMixin, UpdateView):
    template_name = "account/profile.html"
    form_class = UserProfileForm
    model = get_user_model()
    success_message = _('Данные успешно сохранены.')

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("account_profile")

profile = ProfileView.as_view()


class AccountInactiveView(views.AjaxCapableProcessFormViewMixin, FormView):
    form_class = SMSForm
    template_name = 'account/account_inactive.html'
    redirect_field_name = "next"

    def dispatch(self, request, *args, **kwargs):
        if not self.request.session.has_key("last_inactive_user"):
            raise Http404
        if request.method == "GET" and not request.is_ajax() and request.session.has_key("last_inactive_user"):
            request.session['ajax_after_done'] = request.get_full_path()
            return redirect("index:index")
        elif request.POST.get("action") == "send-sms":
            return self.send_sms(request)
        return super(AccountInactiveView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super(AccountInactiveView, self).get_initial()

        try: initial['username'] = self.request.session.get("last_inactive_user")
        except: pass

        return initial

    def send_sms(self, request):
        try: user = get_user_model().objects.get(username=self.request.session.get("last_inactive_user"))
        except: user = None
        if user:
            try:
                sms = SMSConfirmation.objects.filter(user=user)[0]
                if sms.key_expired():
                    sms.send(request)
            except:
                sms = SMSConfirmation.create(user)
                sms.send(request)
        url = reverse("account_inactive")
        next = self.get_success_url()
        if next:
            url+="?%s=%s" % (self.redirect_field_name, next)
        return redirect(url)

    def form_valid(self, form):
        user = get_user_model().objects.get(username=form.cleaned_data['username'])
        user.is_active = True
        user.save()
        try: del self.request.session["last_inactive_user"]
        except: pass
        success_url = self.get_success_url()
        try:
            return form.login(self.request, user, redirect_url=success_url)
        except ImmediateHttpResponse as e:
            return e.response

    def get_success_url(self):
        ret = (get_next_redirect_url(
            self.request,
            self.redirect_field_name) or self.success_url)
        return ret

    def get_context_data(self, **kwargs):
        context = super(AccountInactiveView, self).get_context_data(**kwargs)
        redirect_field_value = get_request_param(self.request,
                                                 self.redirect_field_name)
        if redirect_field_value:
            context["redirect_field_value"] = redirect_field_value
        context["redirect_field_name"] = self.redirect_field_name
        try:
            username = self.request.session.get("last_inactive_user")
            context["sms_expired"] = SMSConfirmation.objects.filter(user__username=username).order_by("-created")[0].key_expired_at()
        except:
            pass

        return context

account_inactive = AccountInactiveView.as_view()


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    model = get_user_model()

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if request.user and not request.user.is_superuser:
            if object.is_public and not object.is_approved:
                raise Http404
            elif not object.is_public:
                raise Http404
        return super(UserDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)

        context["comments"] = Comment.objects.filter(cto=self.object).order_by('-created')
        meeting = Meeting.objects.filter(mfrom=self.request.user, mto=self.object).order_by("-changed")
        if meeting:
            context["meeting"] = meeting[0] # Последняя измененная встреча
        elif self.object.is_public and self.object.is_approved:
            context["form"] = MeetingCreateForm(initial={"mfrom":self.request.user, "mto":self.object})

        return context


@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class ApproveView(AjaxOnlyResponseMixin, UpdateView):
    model = get_user_model()
    form_class = ApproveForm
    template_name = "account_ext/user_approve.html"

    def form_valid(self, form):
        self.object.is_approved = True
        self.object.save()
        return JsonResponse({"location": reverse('person-detail', kwargs={"pk": self.object.pk})})


@method_decorator(login_required, name='dispatch')
class MeetingsListView(ListView):
    model = Meeting

    def get_queryset(self):
        return Meeting.objects.filter(mfrom=self.request.user)

templates/account_ext/user_approve.html
{% extends "base_ajax.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Подтвердить" %}{% endblock title %}

{% block content %}
    <div class="modal-header">
        <h5 class="modal-title">{% trans "Подтвердить" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        Подтвердить данные пользователя?
        <form action="{% url 'person-approve' pk=object.id %}" id="id-approve-form" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="pk" value="{{ object.id }}">
        </form>
    </div>
    <div class="modal-footer">
       <button form="id-approve-form" class="btn btn-primary" type="submit">{% trans "Подтвердить" %}</button>
    </div>
    <script type="text/javascript">
        $("#id-approve-form").submit(function () {
            var form = $(this);
            $.post(
                form.attr('action'),
                form.serialize(),
                function (data) {
                    location.href = data["location"];
                }
            );
            return false;
        });
        $("#id-reset-password, #id-signup").on("click", function () {
            return getModal($(this));
        });
    </script>
{% endblock content %}

templates/account_ext/user_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load socialaccount %}
{% load account_ext %}


{% block title %}{{ object }}{% endblock title %}

{% block content %}
    {% if request.user and request.user.is_superuser and not object.is_approved %}
    <div class="container-fluid bg-danger">
        <div class="container bg-danger">
            <div class="text-center text-white pt-3 pb-3">
                <div class="row">
                    <div class="col-10 text-center">
                        <span>{% trans "Данные публичной личности не подтверждены" %}</span>
                    </div>
                    <div class="col-2 text-right">
                        <a id="id-approve" href="{% url 'person-approve' pk=object.id %}" class="btn btn-outline-secondary">Подтвердить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
        <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#" onclick="history.go(-1)">{% trans "Назад" %}</a></li>
            <li class="breadcrumb-item active">{{ object }}</li>
        </ol>
    </div>
    <div class="container">
        <div class="row pt-5">
            <div class="col-12 col-md-4">
                <img class="big-photo" src="{% if object.photo %}{{ object.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}">
                <p class="text-center mt-3">
                    <input type="number" class="star-rating" value="{{ object.rate|floatformat:0 }}" data-readonly />
                </p>
                {% get_social_accounts object as accounts %}
                {% get_providers as socialaccount_providers %}
                <p class="text-center mt-5">
                    {% for provider in socialaccount_providers %}
                        {% if not provider.id in accounts.keys %}
                        {% else %}
                            {% with accounts|get_item:provider.id as account %}
                                <a class="pl-1 pr-1" href="{{ account.0.get_profile_url }}" target="_blank">
                                    <img class="social" src="{% static 'img/' %}{{ provider.id }}.png"/>
                                </a>
                            {% endwith %}
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="col-12 col-md-8">
                <p class="h1 text-left mt-4"><span class="text-highlighted">{{ object }}</span></p>
                <p class="mt-4">{{ object.about|safe }}</p>
                <p class="mt-4">
                    Категории:
                    {% for category in object.categories.all %}
                        <a href="{% url 'index:category-detail' pk=category.id %}">{{ category }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </p>
                {% if form %}
                <p class="text-left pt-5">
                    <button class="btn btn-primary pl-5 pr-5" type="button" data-toggle="collapse" data-target="#id-collapse-form"
                            aria-expanded="false" aria-controls="id-collapse-form">
                        {% trans 'Мне интересно' %}
                    </button>
                </p>
                {% endif %}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-12">
                {% if form %}
                <div class="collapse2" id="id-collapse-form">
                    <div class="row justify-content-center mt-3">
                        <div class="col-8">
                            {% include "meetings/meeting_form.html" %}
                        </div>
                    </div>
                    <div class="text-center mt-3 pb-3">
                        <button form="id-anketa-form" type="submit" class="btn btn-primary pl-5 pr-5">{% trans 'Отправить заявку' %}</button>
                    </div>
                </div>
                {% elif meeting %}
                    <p class="text-center">
                        <a href="{% url 'meetings:detail' pk=meeting.id %}">{% trans "Ваша заявка N" %}{{ meeting.id }} - {{ meeting.get_state_display }}</a>
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="row justify-content-center mt-3 pb-5">
            <div class="col-12 col-md-8">
                {% for comment in comments %}
                    <div class="media pt-4">
                        <img class="photo d-flex align-self-start mr-3" src="{% if comment.cfrom.photo %}{{ comment.cfrom.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}" alt="Generic placeholder image">
                        <div class="media-body">
                            <p>{{ comment.cfrom }} <small class="mt-0">{{ comment.created }}</small> <input type="number" class="star-rating small-rating" value="{{ comment.rate|floatformat:0 }}" data-readonly /></p>
                            <blockquote class="blockquote">
                                <p class="mb-0">{{ comment.text }}</p>
                            </blockquote>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker-standalone.css' %}" />
{% endblock extra_css %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-rating-input.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment-with-locales.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input.star-rating').rating({
                iconLib: "fa fa-2x",
                activeIcon: "fa-star",
                inactiveIcon: "fa-star-o",
                clearableIcon: "fa-trash-o"
            });

            $("#id-anketa-form").submit(function () {
                var form = $(this);
                $.post(
                    form.attr('action'),
                    form.serialize(),
                    function (data) {
                        if (data["html"]) {
                            $("#id-anketa-form").html(data["html"]);
                        } else {
                            location.reload();
                        }
                    }
                );
                return false;
            });

            $("#id-approve").on("click", function () {
                return getModal($(this));
            });

            $("#id_mdate").datetimepicker({
                locale: 'ru',
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-chevron-up',
                    down: 'fa fa-chevron-down',
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right',
                    today: 'fa fa-desktop',
                    clear: 'fa fa-trash',
                    close: 'fa fa-remove'
                }
            });
        });
    </script>
{% endblock extra_js %}