index/urls.py
from django.conf.urls import url

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category-detail'),
    url(r'^search/$', views.UserSearchView.as_view(), name='person-search'),
]

meetings/urls.py
from django.conf.urls import url

from . import views

app_name = 'meetings'
urlpatterns = [
#    url(r'^anketa/$', views.anketa, name='anketa'),
    url(r'create/$', views.MeetingCreateView.as_view(), name='create'),
    url(r'(?P<pk>\d+)/$', views.MeetingDetailView.as_view(), name='detail'),
]

meetme_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('account_ext.urls')),
    url(r'^', include('allauth.urls')),

    url(r'^', include('index.urls')),
    url(r'^meeting/', include('meetings.urls')),
    url(r'^comment/', include('comments.urls')),

    url(r'^', include('django.contrib.flatpages.urls')),
]

meetings/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import pgettext, ugettext as _
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail

# Create your models here.


class MeetingType(models.Model):
    title = models.CharField(_("Название"), max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Тип встречи')
        verbose_name_plural = _('Типы встречи')


class MeetingGoal(models.Model):
    title = models.CharField(_("Название"), max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Цель встречи')
        verbose_name_plural = _('Цели встречи')

MEETING_STATUSES = [
    (0, _("Новая")),
    (1, _("Согласована")),
    (2, _("Оплачена")),
    (3, _("Проведена")),
    (4, _("Завершена")),
]

class Meeting(models.Model):
    mfrom = models.ForeignKey(get_user_model(), related_name="+", verbose_name=_("Кто"))
    mto = models.ForeignKey(get_user_model(), related_name="+", verbose_name=_("Кому"))
    about = models.TextField(_("Коротко о себе"))
    is_familiar = models.BooleanField(_("Знаете ли вы этого человека"))
    mtype = models.ForeignKey(MeetingType, verbose_name=_("Тип встречи"))
    goal = models.ForeignKey(MeetingGoal, verbose_name=_("Цель встречи"), blank=True, null=True)
    goal_str = models.CharField(_("Другая"), max_length=300, blank=True, null=True)
    mdate = models.DateTimeField(_("Дата и время"))
    is_money = models.BooleanField(_("Готов предложить деньги"))
    money = models.FloatField(_("Сумма"), blank=True, null=True)
    is_other = models.BooleanField(_("Другие ценности"))
    other = models.CharField(_("Описание"), max_length=300, blank=True, null=True)
    state = models.IntegerField(_("Статус"), choices=MEETING_STATUSES, default=0)
    created = models.DateTimeField(_('Создана'), auto_now_add=True)
    changed = models.DateTimeField(_('Изменен статус'), auto_now=True)

    def __str__(self):
        return "%s %s" % (self.mfrom, self.mto)

    class Meta:
        verbose_name = _('Встреча')
        verbose_name_plural = _('Встречи')


@receiver(pre_save, sender=Meeting)
def notify_state_change(sender, **kwargs):
    instance = kwargs.pop("instance")
    if instance.id:
        old_state = instance.__class__.objects.get(id=instance.id).get_state_display()
        if instance.get_state_display() != old_state and instance.mfrom.email:
            current_site = get_current_site(request=None)
            text = 'Статус Вашей заявки изменен с %s на %s. <a href="http://%s%s">Подробнее...</a>' % (old_state, instance.get_state_display(), current_site.domain, reverse('meetings:detail', kwargs={"pk":instance.id}))
            send_mail(
                'Изменение статуса заявки',
                text,
                'no-reply@meetmehub.com',
                [instance.mfrom.email],
                fail_silently=False,
                html_message=text,
            )

meetings/forms.py
import parsedatetime as pdt

from django import forms
from django.utils.translation import pgettext, ugettext as _


from .models import Meeting


class MeetingCreateForm(forms.ModelForm):
    mdate = forms.CharField(label=_("Дата и время"), widget=forms.TextInput(attrs={"type": "text"}))

    class Meta:
        model = Meeting
        fields = '__all__'
        exclude = ["state",]

        widgets = {
            "mfrom": forms.HiddenInput(),
            "mto": forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = super(MeetingCreateForm, self).clean()
        cal = pdt.Calendar()
        date = self.cleaned_data.get('mdate', '').replace("T", " ")
        date, result = cal.parseDT(date)
        cleaned_data["mdate"] = date

        return cleaned_data

meetings/views.py
# coding: utf-8

from django.template.loader import render_to_string
from django.http import JsonResponse, Http404
from django.conf import settings
from django.core.mail import send_mail
from django.views.generic import CreateView, DetailView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.utils.translation import pgettext, ugettext as _
from django.shortcuts import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from comments.forms import CommentForm
from comments.models import Comment
from .forms import MeetingCreateForm
from .models import Meeting

# Create your views here.

class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse({"html": render_to_string(self.template_name, request=self.request, context={"form": form})})
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


template = """
    Заявка на встречу с <a href="%(mto_link)s">%(mto)s</a>

    Меня зовут: <a href="%(mfrom_link)s">%(mfrom)s</a>
    Обо мне: %(about)s

    Знаете ли вы этого человека: %(is_familiar)s
    Тип встречи: %(mtype)s
    Цель встречи: %(goal)s
          другое: %(goal_str)s
    Дата и время: %(mdate)s
    Готов предложить деньги: %(money)s
    Другие ценности: %(other)s
"""

class MeetingCreateView(AjaxableResponseMixin, CreateView):
    model = Meeting
    form_class = MeetingCreateForm
    template_name = "meetings/meeting_form.html"

    def get_success_url(self):
        return "/"

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, _('Заявка успершно создана'))
        mto = form.cleaned_data["mto"]
        mfrom = form.cleaned_data["mfrom"]
        context = form.cleaned_data.copy()
        context.update({
            "mto": str(mto),
            "mto_link": self.request.build_absolute_uri(reverse('person-detail', kwargs={'pk':mto.id})),
            "mfrom": str(mfrom),
            "mfrom_link": self.request.build_absolute_uri(reverse('person-detail', kwargs={'pk':mfrom.id})),
        })
        text = template % context
        send_mail(
            'Заявка',
            text,
            'no-reply@meetmehub.com',
            settings.RECIPIENTS,
            fail_silently=False,
            html_message=text
        )
        return super(MeetingCreateView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.method == "GET" and not request.is_ajax():
            raise Http404
        return super(MeetingCreateView, self).dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class MeetingDetailView(UserPassesTestMixin, DetailView):
    model = Meeting

    def test_func(self):
        return self.request.user.is_superuser or self.request.user == self.get_object().mfrom

    def get_context_data(self, **kwargs):
        context = super(MeetingDetailView, self).get_context_data(**kwargs)

        if self.object.state == 3:
            context["form"] = CommentForm(initial={"cfrom":self.object.mfrom, "cto":self.object.mto})
        elif self.object.state == 4:
            comment = Comment.objects.filter(cfrom=self.object.mfrom, cto=self.object.mto)
            if comment:
                context["comment"] = comment[0]

        return context

templates/meetings/meeting_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#" onclick="history.go(-1)">{% trans "Назад" %}</a></li>
            <li class="breadcrumb-item active">{% trans 'Встреча N' %}{{ object.id }}</li>
        </ol>
    </div>
    <div class="container pb-5">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6">
                <p class="h4">Встреча с <a href="{% url 'person-detail' pk=object.mto.pk %}">{{ object.mto }}</a></p>
                <small>Статус: <strong>{{ object.get_state_display }}</strong> изменен: {{ object.changed }}</small>
                <div class="row mt-5">
                    <div class="col-12 col-md-4">О себе:</div><div class="col-12 col-md-8">{{ object.about }}</div>
                    <div class="col-12 col-md-4">Знаете ли вы этого человека:</div><div class="col-12 col-md-8">{{ object.is_familiar }}</div>
                    <div class="col-12 col-md-4">Цель встречи:</div><div class="col-12 col-md-8">{{ object.goal|default_if_none:"" }}</div>
                    <div class="col-12 col-md-4">Другое:</div><div class="col-12 col-md-8">{{ object.goal_str }}</div>
                    <div class="col-12 col-md-4">Дата и время:</div><div class="col-12 col-md-8">{{ object.mdate }}</div>
                    <div class="col-12 col-md-4">Готов предложить деньги:</div><div class="col-12 col-md-8">{{ object.money|default_if_none:"" }}</div>
                    <div class="col-12 col-md-4">Другие ценности:</div><div class="col-12 col-md-8">{{ object.other|default_if_none:"" }}</div>
                </div>
            </div>
        </div>
        {% if form %}
            <div class="row justify-content-center mt-5">
                <div class="col-12 col-md-6">
                    {% include 'comments/comment_form.html' %}
                    <div class="text-center">
                       <button form="id-add-comment-form" class="btn btn-primary mt-3 pl-5 pr-5" type="submit"
                           data-toggle="tooltip" data-placement="top" title="{% trans 'После завершения встречи Вы не сможете поменять отзыв или оценку' %}"
                       >{% trans "Завершить встречу" %}</button>
                    </div>
                </div>
            </div>
        {% elif comment %}
            <div class="row justify-content-center mt-5">
                <div class="col-12 col-md-6">
                    <input type="number" class="star-rating" value="{{ comment.rate|floatformat:0 }}" data-readonly />
                    <p class="mt-4">{{ comment.text }}</p>
                </div>
            </div>
        {% else %}
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 mt-2">
                    <p class="text-center h4 mt-5">{% trans "После проведения встречи, вы сможете оставить тут свой комментарий" %}</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block extra_js %}
    <script src="{% static 'js/bootstrap-rating-input.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input.star-rating').rating({
                iconLib: "fa fa-2x",
                activeIcon: "fa-star",
                inactiveIcon: "fa-star-o",
                clearableIcon: "fa-trash-o"
            });

            $('[data-toggle="tooltip"]').tooltip();

            $("#id-add-comment-form").submit(function () {
                var form = $(this);
                $.post(
                    form.attr('action'),
                    form.serialize(),
                    function (data) {
                        if (data["html"]) {
                            $("#id-add-comment-form").html(data["html"]);
                        } else {
                            location.reload();
                        }
                    }
                );
                return false;
            });
        });
    </script>
{% endblock extra_js %}

templates/meetings/meeting_form.html
{% load crispy_forms_tags %}

<form id="id-anketa-form" method="POST" action="{% url 'meetings:create' %}">
    {% csrf_token %}
    {{ form|crispy }}
</form>

templates/meetings/meeting_list.html
{% extends "account/base_profile.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Встречи" %}{% endblock title %}

{% block tab_content %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <p class="h1 text-center mb-5"><span class="text-highlighted">{% trans "Встречи" %}</span></p>
            <table data-toggle="table">
                <thead>
                <tr>
                    <th>{% trans "С кем" %}</th>
                    <th>{% trans "Дата встречи" %}</th>
                    <th>{% trans "Статус" %}</th>
                    <th>{% trans "Действие" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td><a href="{% url 'person-detail' pk=object.mto.id %}">{{ object.mto }}</a></td>
                        <td>{{ object.mdate }}</td>
                        <td>{{ object.get_state_display }}<br/><small>{{ object.changed }}</small></td>
                        <td><a href="{% url 'meetings:detail' pk=object.id %}">Подробнее</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock tab_content %}

{% block extra_css %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">
{% endblock extra_css %}

{% block extra_js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js"></script>
{% endblock extra_js %}