index/urls.py
from django.conf.urls import url

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category-detail'),
    url(r'^search/$', views.UserSearchView.as_view(), name='person-search'),
]

meetme_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('account_ext.urls')),
    url(r'^', include('allauth.urls')),

    url(r'^', include('index.urls')),
    url(r'^meeting/', include('meetings.urls')),
    url(r'^comment/', include('comments.urls')),

    url(r'^', include('django.contrib.flatpages.urls')),
]

templates/_nav.html
{% load i18n %}
{% load staticfiles %}

<div id="id-nav" class="container-fluid">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-inverse pt-4">
            <a class="navbar-brand" href="{% url 'index:index' %}"><img class="logo" src="{% static 'img/logo.png' %}"></a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#id-navbar" aria-controls="id-navbar" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="id-navbar">
                <ul class="navbar-nav mr-auto">
                    {% if categories %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="id-category-menu" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                {% trans 'Знаменитости' %}
                            </a>
                            <div class="dropdown-menu wide" aria-labelledby="id-category-menu">
                                <div class="row">
                                    {% for category in categories %}
                                        <div class="col-12 col-md-6 pt-3 pb-3">
                                            <a href="{% url 'index:category-detail' pk=category.id %}"
                                               class="col-12 col-md-4 text-center styled-link">
                                                <img class="category-icon-small pr-2" src="{{ category.image.url }}">
                                                <span class="text-white">{{ category.title }} </span>
                                                <span class="badge badge-pill badge-default float-right pt-1 mt-1 mr-2">{{ category.users_count }}</span>
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="id-user-menu" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <img class="photo" src="
                                        {% if request.user.photo %}{{ request.user.photo.url }}{% else %}{% static 'img/nophoto.png' %}{% endif %}"/>
                                {{ request.user }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="id-user-menu">
                                <a class="text-white dropdown-item"
                                   href="{% url 'account_profile' %}">{% trans 'Профиль' %}</a>
                                <a class="text-white dropdown-item"
                                   href="{% url 'account_logout' %}">{% trans "Выход" %}</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a id="id-login" class="nav-link" href="{% url 'account_login' %}">{% trans "Вход" %}</a>
                        </li>
                        <li class="nav-item">
                            <a id="id-signup" class="nav-link"
                               href="{% url 'account_signup' %}">{% trans "Регистрация" %}</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav my-2 my-md-0 d-flex flex-md-column-reverse flex-lg-row">
                    <li class="nav-item align-self-center mr-4">
                        <form id="id-form-search" action="{% url 'index:person-search' %}"
                              class="form-inline mt-2 mt-md-0">
                            <div class="input-group">
                                <input type="text" class="form-control" name="q" placeholder="{% trans 'Найти...' %}">
                                <span class="input-group-btn">
                                        <button class="btn btn-secondary" type="submit"><i
                                                class="fa fa-lg fa-search"></i></button>
                                    </span>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load flatblocks %}
{% load flatpages %}
{% get_flatpages as flatpages %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}meetme{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <meta property="og:title" content="Meetmehub.com"/>
    <meta property="og:site_name" content="Meetmehub.com"/>
    <meta name="description"
          content="Описание портала для знакомств"/>
    <meta property="og:description"
          content="Описание портала для знакомств"/>
    <meta property="og:url" content="meetmehub.com"/>
    <meta property="og:image" content="{% static 'img/logo.png' %}"/>
    <meta property="og:image:width" content="479"/>
    <meta property="og:image:height" content="638"/>
    <meta name="keywords"
          content="привлечь инвестиции, инвестировать, краудинвестинг, инвестиционная платформа tugush"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap.min.css' %}">
    {% block extra_css %}{% endblock extra_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div id="id-messages" class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    </div>
    {% include '_nav.html' %}
    {% block content %}
    {% endblock content %}
    {% block content_index %}
    {% endblock content_index %}
    <footer class="container-fluid text-center pt-5">
        <div class="container">
            <div class="row pt-3">
                <div class="col-12 col-md-3 footer-col">
                    <div class="h6"><img class="logo" src="{% static 'img/logo.png' %}"></div>
                    <div class="">{% flatblock 'info.address' %}</div>
                    <div class="">{% flatblock 'info.phone' %}</div>
                    <div class="">{% flatblock 'info.email' %}</div>
                </div>
                <div class="col-12 col-md-3 footer-col">
                    <div class="h6 pt-4 text-white">{% flatblock 'docs' %}</div>
                    {% for page in flatpages %}
                        <div><a class="text-white" href="{{ page.url }}">{{ page.title }}</a></div>
                    {% endfor %}
                </div>
                <div class="col-12 col-md-3 footer-col">
                    <div class="h6 pt-4 text-white">{% flatblock 'other' %}</div>
                    <div class="text-white">{% flatblock 'other.text' %}</div>
                </div>
                <div class="col-12 col-md-3 text-center socials">
                    <!-- <a href="#" class="fa fa-3x fa-vk pt-5 pb-5">&nbsp;</a> -->
                    <a href="#" target="_blank" class="fa fa-3x fa-facebook pt-5 pb-5">&nbsp;</a>
                    <a href="https://www.instagram.com/meetmehub/" target="_blank" class="fa fa-3x fa-instagram pt-5 pb-5">&nbsp;</a>
                </div>
            </div>
            <div class="row mt-3 pb-4">
                <div class="col-12">
                    <div class="footer-text">{% flatblock 'footer.text' evaluated=True %}</div>
                    <div class="footer-copyright">{% flatblock 'footer.copyright' evaluated=True %}</div>
                </div>
            </div>
        </div>
    </footer>
    {% block modals %}
        <div id="id-modal" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Modal body text goes here.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Save changes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endblock modals %}
<!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{% static 'js/inputmask/inputmask.min.js' %}"></script>
    <script src="{% static 'js/inputmask/inputmask.phone.extensions.min.js' %}"></script>
    <script src="{% static 'js/inputmask/jquery.inputmask.min.js' %}"></script>
    <script src="{% static 'js/inputmask/phone-codes/phone.min.js' %}"></script>
    <script src="{% static 'js/inputmask/phone-codes/phone-be.min.js' %}"></script>
    <script src="{% static 'js/inputmask/phone-codes/phone-ru.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.countdown.min.js' %}"></script>
    {% block extra_js %}{% endblock extra_js %}
    <script type="text/javascript">
        function getModal(a) {
            $.get(
                $(a).attr("href"),
                function (data) {
                    $("#id-modal .modal-content").html(data["html"]);
                    if ($("#id-modal").is(":visible") == false) {
                        $("#id-modal").modal('show');
                    }
                }
            );
            return false;
        }
        $(document).ready(function () {
            $("#id-login, #id-signup, #id-signup-public").on("click", function () {
                return getModal($(this));
            });
            setTimeout(function () {$(".alert").slideUp(500)}, 3500);
        })
    </script>
</body>
</html>

templates/base_ajax.html
{% block content %}{% endblock content %}